spring:
  application:
    name: delay-job
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.114.83:3306/delay_job?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Findthinks@2022
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      pool-name: DelayJobPool
      connection-test-query: SELECT 1
  jackson:
    default-property-inclusion: non_null
server:
  port: 1989
grpc:
  server:
    port: 1990
  executor:
    num: 50
scheduler:
  judge-dead: 15
  cron:
    heartbeat: 2,7,12,17,22,27,32,37,42,47,52,57 * * * * ?
  job:
    cron:
      load: 0 0/1 * * * ?
      retry: 5,15,25,35,45,55 * * * * ?
      sync-state: 5,15,25,35,45,55 * * * * ?
      translate: 10,25,40,55 * * * * ?
    load-max-num: 20000
    translate-max-num: 100
    once-retry-seg-num: 10
    retry-max-num: 1000
    retry-seg-num: 60
    state-check-seg-num: 10
    http-trigger-connect-timeout: 1
    http-trigger-read-timeout: 1
logging:
  file:
    name: classpath:logback.xml
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml