spring:
  application:
    name: delay-job
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.87.4:3306/delay_job?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: bbfisher
    password: Bbfisher123!
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      pool-name: DelayJobPool
      connection-test-query: SELECT 1
  jackson:
    default-property-inclusion: non_null
server:
  port: 1989
grpc:
  server:
    port: 1990
  executor:
    num: 50
scheduler:
  judge-dead: 15
  cron:
    heartbeat: 2,7,12,17,22,27,32,37,42,47,52,57 * * * * ?
  job:
    cron:
      load: 0 0/1 * * * ?
      retry: 5,15,25,35,45,55 * * * * ?
      sync-state: 5,15,25,35,45,55 * * * * ?
      translate: 10,25,40,55 * * * * ?
    load-max-nums: 50000
    repeat-check-delta: 5
    translate-max-nums: 100
    once-retry-seg-nums: 10
    retry-max-nums: 10000
    retry-seg-nums: 1440
    state-check-seg-nums: 10
    http-trigger-connect-timeout: 1
    http-trigger-read-timeout: 1
logging:
  file:
    name: classpath:logback.xml
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml