// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJob.proto

package com.findthinks.delay.job.proto.mgr;

public interface CancelJobReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CancelJobReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string outJobNo = 1;</code>
   * @return The outJobNo.
   */
  java.lang.String getOutJobNo();
  /**
   * <code>string outJobNo = 1;</code>
   * @return The bytes for outJobNo.
   */
  com.google.protobuf.ByteString
      getOutJobNoBytes();
}
