// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJob.proto

package com.findthinks.delay.job.proto.mgr;

public interface CreateJobReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CreateJobReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string outJobNo = 1;</code>
   * @return The outJobNo.
   */
  java.lang.String getOutJobNo();
  /**
   * <code>string outJobNo = 1;</code>
   * @return The bytes for outJobNo.
   */
  com.google.protobuf.ByteString
      getOutJobNoBytes();

  /**
   * <code>int64 triggerTime = 2;</code>
   * @return The triggerTime.
   */
  long getTriggerTime();

  /**
   * <code>string callbackProtocol = 3;</code>
   * @return The callbackProtocol.
   */
  java.lang.String getCallbackProtocol();
  /**
   * <code>string callbackProtocol = 3;</code>
   * @return The bytes for callbackProtocol.
   */
  com.google.protobuf.ByteString
      getCallbackProtocolBytes();

  /**
   * <code>string callbackEndpoint = 4;</code>
   * @return The callbackEndpoint.
   */
  java.lang.String getCallbackEndpoint();
  /**
   * <code>string callbackEndpoint = 4;</code>
   * @return The bytes for callbackEndpoint.
   */
  com.google.protobuf.ByteString
      getCallbackEndpointBytes();

  /**
   * <code>string jobInfo = 5;</code>
   * @return The jobInfo.
   */
  java.lang.String getJobInfo();
  /**
   * <code>string jobInfo = 5;</code>
   * @return The bytes for jobInfo.
   */
  com.google.protobuf.ByteString
      getJobInfoBytes();
}
