// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJob.proto

package com.findthinks.delay.job.proto.mgr;

/**
 * Protobuf type {@code delay.job.CreateJobReq}
 */
public final class CreateJobReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:delay.job.CreateJobReq)
    CreateJobReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateJobReq.newBuilder() to construct.
  private CreateJobReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateJobReq() {
    outJobNo_ = "";
    callbackProtocol_ = "";
    callbackEndpoint_ = "";
    jobInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateJobReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateJobReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            outJobNo_ = s;
            break;
          }
          case 16: {

            triggerTime_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            callbackProtocol_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            callbackEndpoint_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            jobInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.findthinks.delay.job.proto.mgr.DelayJobOuterClass.internal_static_delay_job_CreateJobReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.findthinks.delay.job.proto.mgr.DelayJobOuterClass.internal_static_delay_job_CreateJobReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.findthinks.delay.job.proto.mgr.CreateJobReq.class, com.findthinks.delay.job.proto.mgr.CreateJobReq.Builder.class);
  }

  public static final int OUTJOBNO_FIELD_NUMBER = 1;
  private volatile java.lang.Object outJobNo_;
  /**
   * <code>string outJobNo = 1;</code>
   * @return The outJobNo.
   */
  @java.lang.Override
  public java.lang.String getOutJobNo() {
    java.lang.Object ref = outJobNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outJobNo_ = s;
      return s;
    }
  }
  /**
   * <code>string outJobNo = 1;</code>
   * @return The bytes for outJobNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutJobNoBytes() {
    java.lang.Object ref = outJobNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outJobNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRIGGERTIME_FIELD_NUMBER = 2;
  private long triggerTime_;
  /**
   * <code>int64 triggerTime = 2;</code>
   * @return The triggerTime.
   */
  @java.lang.Override
  public long getTriggerTime() {
    return triggerTime_;
  }

  public static final int CALLBACKPROTOCOL_FIELD_NUMBER = 3;
  private volatile java.lang.Object callbackProtocol_;
  /**
   * <code>string callbackProtocol = 3;</code>
   * @return The callbackProtocol.
   */
  @java.lang.Override
  public java.lang.String getCallbackProtocol() {
    java.lang.Object ref = callbackProtocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callbackProtocol_ = s;
      return s;
    }
  }
  /**
   * <code>string callbackProtocol = 3;</code>
   * @return The bytes for callbackProtocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallbackProtocolBytes() {
    java.lang.Object ref = callbackProtocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callbackProtocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLBACKENDPOINT_FIELD_NUMBER = 4;
  private volatile java.lang.Object callbackEndpoint_;
  /**
   * <code>string callbackEndpoint = 4;</code>
   * @return The callbackEndpoint.
   */
  @java.lang.Override
  public java.lang.String getCallbackEndpoint() {
    java.lang.Object ref = callbackEndpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callbackEndpoint_ = s;
      return s;
    }
  }
  /**
   * <code>string callbackEndpoint = 4;</code>
   * @return The bytes for callbackEndpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallbackEndpointBytes() {
    java.lang.Object ref = callbackEndpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callbackEndpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOBINFO_FIELD_NUMBER = 5;
  private volatile java.lang.Object jobInfo_;
  /**
   * <code>string jobInfo = 5;</code>
   * @return The jobInfo.
   */
  @java.lang.Override
  public java.lang.String getJobInfo() {
    java.lang.Object ref = jobInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string jobInfo = 5;</code>
   * @return The bytes for jobInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobInfoBytes() {
    java.lang.Object ref = jobInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOutJobNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, outJobNo_);
    }
    if (triggerTime_ != 0L) {
      output.writeInt64(2, triggerTime_);
    }
    if (!getCallbackProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, callbackProtocol_);
    }
    if (!getCallbackEndpointBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, callbackEndpoint_);
    }
    if (!getJobInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, jobInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOutJobNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, outJobNo_);
    }
    if (triggerTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, triggerTime_);
    }
    if (!getCallbackProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, callbackProtocol_);
    }
    if (!getCallbackEndpointBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, callbackEndpoint_);
    }
    if (!getJobInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, jobInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.findthinks.delay.job.proto.mgr.CreateJobReq)) {
      return super.equals(obj);
    }
    com.findthinks.delay.job.proto.mgr.CreateJobReq other = (com.findthinks.delay.job.proto.mgr.CreateJobReq) obj;

    if (!getOutJobNo()
        .equals(other.getOutJobNo())) return false;
    if (getTriggerTime()
        != other.getTriggerTime()) return false;
    if (!getCallbackProtocol()
        .equals(other.getCallbackProtocol())) return false;
    if (!getCallbackEndpoint()
        .equals(other.getCallbackEndpoint())) return false;
    if (!getJobInfo()
        .equals(other.getJobInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OUTJOBNO_FIELD_NUMBER;
    hash = (53 * hash) + getOutJobNo().hashCode();
    hash = (37 * hash) + TRIGGERTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTriggerTime());
    hash = (37 * hash) + CALLBACKPROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getCallbackProtocol().hashCode();
    hash = (37 * hash) + CALLBACKENDPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getCallbackEndpoint().hashCode();
    hash = (37 * hash) + JOBINFO_FIELD_NUMBER;
    hash = (53 * hash) + getJobInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.findthinks.delay.job.proto.mgr.CreateJobReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.findthinks.delay.job.proto.mgr.CreateJobReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code delay.job.CreateJobReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:delay.job.CreateJobReq)
      com.findthinks.delay.job.proto.mgr.CreateJobReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.findthinks.delay.job.proto.mgr.DelayJobOuterClass.internal_static_delay_job_CreateJobReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.findthinks.delay.job.proto.mgr.DelayJobOuterClass.internal_static_delay_job_CreateJobReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.findthinks.delay.job.proto.mgr.CreateJobReq.class, com.findthinks.delay.job.proto.mgr.CreateJobReq.Builder.class);
    }

    // Construct using com.findthinks.delay.job.proto.mgr.CreateJobReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      outJobNo_ = "";

      triggerTime_ = 0L;

      callbackProtocol_ = "";

      callbackEndpoint_ = "";

      jobInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.findthinks.delay.job.proto.mgr.DelayJobOuterClass.internal_static_delay_job_CreateJobReq_descriptor;
    }

    @java.lang.Override
    public com.findthinks.delay.job.proto.mgr.CreateJobReq getDefaultInstanceForType() {
      return com.findthinks.delay.job.proto.mgr.CreateJobReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.findthinks.delay.job.proto.mgr.CreateJobReq build() {
      com.findthinks.delay.job.proto.mgr.CreateJobReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.findthinks.delay.job.proto.mgr.CreateJobReq buildPartial() {
      com.findthinks.delay.job.proto.mgr.CreateJobReq result = new com.findthinks.delay.job.proto.mgr.CreateJobReq(this);
      result.outJobNo_ = outJobNo_;
      result.triggerTime_ = triggerTime_;
      result.callbackProtocol_ = callbackProtocol_;
      result.callbackEndpoint_ = callbackEndpoint_;
      result.jobInfo_ = jobInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.findthinks.delay.job.proto.mgr.CreateJobReq) {
        return mergeFrom((com.findthinks.delay.job.proto.mgr.CreateJobReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.findthinks.delay.job.proto.mgr.CreateJobReq other) {
      if (other == com.findthinks.delay.job.proto.mgr.CreateJobReq.getDefaultInstance()) return this;
      if (!other.getOutJobNo().isEmpty()) {
        outJobNo_ = other.outJobNo_;
        onChanged();
      }
      if (other.getTriggerTime() != 0L) {
        setTriggerTime(other.getTriggerTime());
      }
      if (!other.getCallbackProtocol().isEmpty()) {
        callbackProtocol_ = other.callbackProtocol_;
        onChanged();
      }
      if (!other.getCallbackEndpoint().isEmpty()) {
        callbackEndpoint_ = other.callbackEndpoint_;
        onChanged();
      }
      if (!other.getJobInfo().isEmpty()) {
        jobInfo_ = other.jobInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.findthinks.delay.job.proto.mgr.CreateJobReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.findthinks.delay.job.proto.mgr.CreateJobReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object outJobNo_ = "";
    /**
     * <code>string outJobNo = 1;</code>
     * @return The outJobNo.
     */
    public java.lang.String getOutJobNo() {
      java.lang.Object ref = outJobNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outJobNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string outJobNo = 1;</code>
     * @return The bytes for outJobNo.
     */
    public com.google.protobuf.ByteString
        getOutJobNoBytes() {
      java.lang.Object ref = outJobNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outJobNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string outJobNo = 1;</code>
     * @param value The outJobNo to set.
     * @return This builder for chaining.
     */
    public Builder setOutJobNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outJobNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string outJobNo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutJobNo() {
      
      outJobNo_ = getDefaultInstance().getOutJobNo();
      onChanged();
      return this;
    }
    /**
     * <code>string outJobNo = 1;</code>
     * @param value The bytes for outJobNo to set.
     * @return This builder for chaining.
     */
    public Builder setOutJobNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outJobNo_ = value;
      onChanged();
      return this;
    }

    private long triggerTime_ ;
    /**
     * <code>int64 triggerTime = 2;</code>
     * @return The triggerTime.
     */
    @java.lang.Override
    public long getTriggerTime() {
      return triggerTime_;
    }
    /**
     * <code>int64 triggerTime = 2;</code>
     * @param value The triggerTime to set.
     * @return This builder for chaining.
     */
    public Builder setTriggerTime(long value) {
      
      triggerTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 triggerTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTriggerTime() {
      
      triggerTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object callbackProtocol_ = "";
    /**
     * <code>string callbackProtocol = 3;</code>
     * @return The callbackProtocol.
     */
    public java.lang.String getCallbackProtocol() {
      java.lang.Object ref = callbackProtocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callbackProtocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string callbackProtocol = 3;</code>
     * @return The bytes for callbackProtocol.
     */
    public com.google.protobuf.ByteString
        getCallbackProtocolBytes() {
      java.lang.Object ref = callbackProtocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callbackProtocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string callbackProtocol = 3;</code>
     * @param value The callbackProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setCallbackProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callbackProtocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string callbackProtocol = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallbackProtocol() {
      
      callbackProtocol_ = getDefaultInstance().getCallbackProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string callbackProtocol = 3;</code>
     * @param value The bytes for callbackProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setCallbackProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callbackProtocol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object callbackEndpoint_ = "";
    /**
     * <code>string callbackEndpoint = 4;</code>
     * @return The callbackEndpoint.
     */
    public java.lang.String getCallbackEndpoint() {
      java.lang.Object ref = callbackEndpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callbackEndpoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string callbackEndpoint = 4;</code>
     * @return The bytes for callbackEndpoint.
     */
    public com.google.protobuf.ByteString
        getCallbackEndpointBytes() {
      java.lang.Object ref = callbackEndpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callbackEndpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string callbackEndpoint = 4;</code>
     * @param value The callbackEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setCallbackEndpoint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callbackEndpoint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string callbackEndpoint = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCallbackEndpoint() {
      
      callbackEndpoint_ = getDefaultInstance().getCallbackEndpoint();
      onChanged();
      return this;
    }
    /**
     * <code>string callbackEndpoint = 4;</code>
     * @param value The bytes for callbackEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setCallbackEndpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callbackEndpoint_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobInfo_ = "";
    /**
     * <code>string jobInfo = 5;</code>
     * @return The jobInfo.
     */
    public java.lang.String getJobInfo() {
      java.lang.Object ref = jobInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jobInfo = 5;</code>
     * @return The bytes for jobInfo.
     */
    public com.google.protobuf.ByteString
        getJobInfoBytes() {
      java.lang.Object ref = jobInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jobInfo = 5;</code>
     * @param value The jobInfo to set.
     * @return This builder for chaining.
     */
    public Builder setJobInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jobInfo = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobInfo() {
      
      jobInfo_ = getDefaultInstance().getJobInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string jobInfo = 5;</code>
     * @param value The bytes for jobInfo to set.
     * @return This builder for chaining.
     */
    public Builder setJobInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:delay.job.CreateJobReq)
  }

  // @@protoc_insertion_point(class_scope:delay.job.CreateJobReq)
  private static final com.findthinks.delay.job.proto.mgr.CreateJobReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.findthinks.delay.job.proto.mgr.CreateJobReq();
  }

  public static com.findthinks.delay.job.proto.mgr.CreateJobReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateJobReq>
      PARSER = new com.google.protobuf.AbstractParser<CreateJobReq>() {
    @java.lang.Override
    public CreateJobReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateJobReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateJobReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateJobReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.findthinks.delay.job.proto.mgr.CreateJobReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

