// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJob.proto

package com.findthinks.delay.job.proto.mgr;

public interface CreateJobsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CreateJobsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  java.util.List<com.findthinks.delay.job.proto.mgr.CreateJobReq> 
      getJobsList();
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  com.findthinks.delay.job.proto.mgr.CreateJobReq getJobs(int index);
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  java.util.List<? extends com.findthinks.delay.job.proto.mgr.CreateJobReqOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  com.findthinks.delay.job.proto.mgr.CreateJobReqOrBuilder getJobsOrBuilder(
      int index);
}
