// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJob.proto

package com.findthinks.delay.job.proto.mgr;

public final class DelayJobOuterClass {
  private DelayJobOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CreateJobReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CreateJobReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CreateJobsReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CreateJobsReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CancelJobReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CancelJobReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_JobResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_JobResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DelayJob.proto\022\tdelay.job\"z\n\014CreateJob" +
      "Req\022\020\n\010outJobNo\030\001 \001(\t\022\023\n\013triggerTime\030\002 \001" +
      "(\003\022\030\n\020callbackProtocol\030\003 \001(\t\022\030\n\020callback" +
      "Endpoint\030\004 \001(\t\022\017\n\007jobInfo\030\005 \001(\t\"6\n\rCreat" +
      "eJobsReq\022%\n\004jobs\030\001 \003(\0132\027.delay.job.Creat" +
      "eJobReq\" \n\014CancelJobReq\022\020\n\010outJobNo\030\001 \001(" +
      "\t\"(\n\007JobResp\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 " +
      "\001(\t2\300\001\n\010DelayJob\022:\n\tsubmitJob\022\027.delay.jo" +
      "b.CreateJobReq\032\022.delay.job.JobResp\"\000\022<\n\n" +
      "submitJobs\022\030.delay.job.CreateJobsReq\032\022.d" +
      "elay.job.JobResp\"\000\022:\n\tcancelJob\022\027.delay." +
      "job.CancelJobReq\032\022.delay.job.JobResp\"\000B&" +
      "\n\"com.findthinks.delay.job.proto.mgrP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_delay_job_CreateJobReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_delay_job_CreateJobReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CreateJobReq_descriptor,
        new java.lang.String[] { "OutJobNo", "TriggerTime", "CallbackProtocol", "CallbackEndpoint", "JobInfo", });
    internal_static_delay_job_CreateJobsReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_delay_job_CreateJobsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CreateJobsReq_descriptor,
        new java.lang.String[] { "Jobs", });
    internal_static_delay_job_CancelJobReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_delay_job_CancelJobReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CancelJobReq_descriptor,
        new java.lang.String[] { "OutJobNo", });
    internal_static_delay_job_JobResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_delay_job_JobResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_JobResp_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
