// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.findthinks.delay.job.facade.grpc.mgr;

/**
 * Protobuf type {@code delay.job.CreateJobsReq}
 */
public final class CreateJobsReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:delay.job.CreateJobsReq)
    CreateJobsReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateJobsReq.newBuilder() to construct.
  private CreateJobsReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateJobsReq() {
    jobs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateJobsReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateJobsReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobs_ = new java.util.ArrayList<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobs_.add(
                input.readMessage(com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobs_ = java.util.Collections.unmodifiableList(jobs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.findthinks.delay.job.facade.grpc.mgr.JobOuterClass.internal_static_delay_job_CreateJobsReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.findthinks.delay.job.facade.grpc.mgr.JobOuterClass.internal_static_delay_job_CreateJobsReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.class, com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.Builder.class);
  }

  public static final int JOBS_FIELD_NUMBER = 1;
  private java.util.List<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq> jobs_;
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq> getJobsList() {
    return jobs_;
  }
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder> 
      getJobsOrBuilderList() {
    return jobs_;
  }
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  @java.lang.Override
  public int getJobsCount() {
    return jobs_.size();
  }
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  @java.lang.Override
  public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq getJobs(int index) {
    return jobs_.get(index);
  }
  /**
   * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
   */
  @java.lang.Override
  public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder getJobsOrBuilder(
      int index) {
    return jobs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobs_.size(); i++) {
      output.writeMessage(1, jobs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq)) {
      return super.equals(obj);
    }
    com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq other = (com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq) obj;

    if (!getJobsList()
        .equals(other.getJobsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobsCount() > 0) {
      hash = (37 * hash) + JOBS_FIELD_NUMBER;
      hash = (53 * hash) + getJobsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code delay.job.CreateJobsReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:delay.job.CreateJobsReq)
      com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.findthinks.delay.job.facade.grpc.mgr.JobOuterClass.internal_static_delay_job_CreateJobsReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.findthinks.delay.job.facade.grpc.mgr.JobOuterClass.internal_static_delay_job_CreateJobsReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.class, com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.Builder.class);
    }

    // Construct using com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.findthinks.delay.job.facade.grpc.mgr.JobOuterClass.internal_static_delay_job_CreateJobsReq_descriptor;
    }

    @java.lang.Override
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq getDefaultInstanceForType() {
      return com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq build() {
      com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq buildPartial() {
      com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq result = new com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq(this);
      int from_bitField0_ = bitField0_;
      if (jobsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobs_ = jobs_;
      } else {
        result.jobs_ = jobsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq) {
        return mergeFrom((com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq other) {
      if (other == com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq.getDefaultInstance()) return this;
      if (jobsBuilder_ == null) {
        if (!other.jobs_.isEmpty()) {
          if (jobs_.isEmpty()) {
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobsIsMutable();
            jobs_.addAll(other.jobs_);
          }
          onChanged();
        }
      } else {
        if (!other.jobs_.isEmpty()) {
          if (jobsBuilder_.isEmpty()) {
            jobsBuilder_.dispose();
            jobsBuilder_ = null;
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobsFieldBuilder() : null;
          } else {
            jobsBuilder_.addAllMessages(other.jobs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq> jobs_ =
      java.util.Collections.emptyList();
    private void ensureJobsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobs_ = new java.util.ArrayList<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq>(jobs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder> jobsBuilder_;

    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public java.util.List<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq> getJobsList() {
      if (jobsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobs_);
      } else {
        return jobsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public int getJobsCount() {
      if (jobsBuilder_ == null) {
        return jobs_.size();
      } else {
        return jobsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq getJobs(int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);
      } else {
        return jobsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder setJobs(
        int index, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.set(index, value);
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder setJobs(
        int index, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder addJobs(com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder addJobs(
        int index, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(index, value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder addJobs(
        com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder addJobs(
        int index, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder addAllJobs(
        java.lang.Iterable<? extends com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq> values) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobs_);
        onChanged();
      } else {
        jobsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder clearJobs() {
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public Builder removeJobs(int index) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.remove(index);
        onChanged();
      } else {
        jobsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder getJobsBuilder(
        int index) {
      return getJobsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder getJobsOrBuilder(
        int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);  } else {
        return jobsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public java.util.List<? extends com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder> 
         getJobsOrBuilderList() {
      if (jobsBuilder_ != null) {
        return jobsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobs_);
      }
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder addJobsBuilder() {
      return getJobsFieldBuilder().addBuilder(
          com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.getDefaultInstance());
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder addJobsBuilder(
        int index) {
      return getJobsFieldBuilder().addBuilder(
          index, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.getDefaultInstance());
    }
    /**
     * <code>repeated .delay.job.CreateJobReq jobs = 1;</code>
     */
    public java.util.List<com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder> 
         getJobsBuilderList() {
      return getJobsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder> 
        getJobsFieldBuilder() {
      if (jobsBuilder_ == null) {
        jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReq.Builder, com.findthinks.delay.job.facade.grpc.mgr.CreateJobReqOrBuilder>(
                jobs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobs_ = null;
      }
      return jobsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:delay.job.CreateJobsReq)
  }

  // @@protoc_insertion_point(class_scope:delay.job.CreateJobsReq)
  private static final com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq();
  }

  public static com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateJobsReq>
      PARSER = new com.google.protobuf.AbstractParser<CreateJobsReq>() {
    @java.lang.Override
    public CreateJobsReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateJobsReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateJobsReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateJobsReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.findthinks.delay.job.facade.grpc.mgr.CreateJobsReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

