// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Job.proto

package com.findthinks.delay.job.facade.grpc.mgr;

public interface JobRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.JobResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应业务编码：ok(成功)，其它为失败
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * 响应业务编码：ok(成功)，其它为失败
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * 响应描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 响应描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
