// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJobCallback.proto

package com.findthinks.delay.job.proto.cb;

public interface CallbackRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CallbackResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
