// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DelayJobCallback.proto

package com.findthinks.delay.job.proto.cb;

public final class DelayJobCallbackOuterClass {
  private DelayJobCallbackOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_JobCallbackReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_JobCallbackReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CallbackResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CallbackResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026DelayJobCallback.proto\022\tdelay.job\"H\n\016J" +
      "obCallbackReq\022\020\n\010outJobNo\030\001 \001(\t\022\023\n\013trigg" +
      "erTime\030\002 \001(\003\022\017\n\007jobInfo\030\003 \001(\t\"-\n\014Callbac" +
      "kResp\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2S\n\020" +
      "DelayJobCallback\022?\n\007trigger\022\031.delay.job." +
      "JobCallbackReq\032\027.delay.job.CallbackResp\"" +
      "\000B%\n!com.findthinks.delay.job.proto.cbP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_delay_job_JobCallbackReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_delay_job_JobCallbackReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_JobCallbackReq_descriptor,
        new java.lang.String[] { "OutJobNo", "TriggerTime", "JobInfo", });
    internal_static_delay_job_CallbackResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_delay_job_CallbackResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CallbackResp_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
