// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobCallback.proto

package com.findthinks.delay.job.facade.grpc.cb;

public interface CallbackJobInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CallbackJobInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string outJobNo = 1;</code>
   * @return The outJobNo.
   */
  java.lang.String getOutJobNo();
  /**
   * <code>string outJobNo = 1;</code>
   * @return The bytes for outJobNo.
   */
  com.google.protobuf.ByteString
      getOutJobNoBytes();

  /**
   * <code>int64 triggerTime = 2;</code>
   * @return The triggerTime.
   */
  long getTriggerTime();

  /**
   * <code>string jobInfo = 3;</code>
   * @return The jobInfo.
   */
  java.lang.String getJobInfo();
  /**
   * <code>string jobInfo = 3;</code>
   * @return The bytes for jobInfo.
   */
  com.google.protobuf.ByteString
      getJobInfoBytes();
}
