// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobCallback.proto

package com.findthinks.delay.job.facade.grpc.cb;

public interface CallbackReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CallbackReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 外部任务编号（长度32位内字符串）
   * </pre>
   *
   * <code>string outJobNo = 1;</code>
   * @return The outJobNo.
   */
  java.lang.String getOutJobNo();
  /**
   * <pre>
   * 外部任务编号（长度32位内字符串）
   * </pre>
   *
   * <code>string outJobNo = 1;</code>
   * @return The bytes for outJobNo.
   */
  com.google.protobuf.ByteString
      getOutJobNoBytes();

  /**
   * <pre>
   * 触发时间（秒）
   * </pre>
   *
   * <code>int64 triggerTime = 2;</code>
   * @return The triggerTime.
   */
  long getTriggerTime();

  /**
   * <pre>
   * 透传参数
   * </pre>
   *
   * <code>string jobInfo = 3;</code>
   * @return The jobInfo.
   */
  java.lang.String getJobInfo();
  /**
   * <pre>
   * 透传参数
   * </pre>
   *
   * <code>string jobInfo = 3;</code>
   * @return The bytes for jobInfo.
   */
  com.google.protobuf.ByteString
      getJobInfoBytes();
}
