// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobCallback.proto

package com.findthinks.delay.job.facade.grpc.cb;

public interface CallbackReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:delay.job.CallbackReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .delay.job.CallbackJobInfo jobs = 1;</code>
   */
  java.util.List<com.findthinks.delay.job.facade.grpc.cb.CallbackJobInfo> 
      getJobsList();
  /**
   * <code>repeated .delay.job.CallbackJobInfo jobs = 1;</code>
   */
  com.findthinks.delay.job.facade.grpc.cb.CallbackJobInfo getJobs(int index);
  /**
   * <code>repeated .delay.job.CallbackJobInfo jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <code>repeated .delay.job.CallbackJobInfo jobs = 1;</code>
   */
  java.util.List<? extends com.findthinks.delay.job.facade.grpc.cb.CallbackJobInfoOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <code>repeated .delay.job.CallbackJobInfo jobs = 1;</code>
   */
  com.findthinks.delay.job.facade.grpc.cb.CallbackJobInfoOrBuilder getJobsOrBuilder(
      int index);
}
