// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobCallback.proto

package com.findthinks.delay.job.facade.grpc.cb;

public final class JobCallbackOuterClass {
  private JobCallbackOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CallbackJobInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CallbackJobInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CallbackReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CallbackReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_delay_job_CallbackResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_delay_job_CallbackResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021JobCallback.proto\022\tdelay.job\"I\n\017Callba" +
      "ckJobInfo\022\020\n\010outJobNo\030\001 \001(\t\022\023\n\013triggerTi" +
      "me\030\002 \001(\003\022\017\n\007jobInfo\030\003 \001(\t\"7\n\013CallbackReq" +
      "\022(\n\004jobs\030\001 \003(\0132\032.delay.job.CallbackJobIn" +
      "fo\"-\n\014CallbackResp\022\014\n\004code\030\001 \001(\t\022\017\n\007mess" +
      "age\030\002 \001(\t2K\n\013JobCallback\022<\n\007trigger\022\026.de" +
      "lay.job.CallbackReq\032\027.delay.job.Callback" +
      "Resp\"\000B+\n\'com.findthinks.delay.job.facad" +
      "e.grpc.cbP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_delay_job_CallbackJobInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_delay_job_CallbackJobInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CallbackJobInfo_descriptor,
        new java.lang.String[] { "OutJobNo", "TriggerTime", "JobInfo", });
    internal_static_delay_job_CallbackReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_delay_job_CallbackReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CallbackReq_descriptor,
        new java.lang.String[] { "Jobs", });
    internal_static_delay_job_CallbackResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_delay_job_CallbackResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_delay_job_CallbackResp_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
